### ISSUE TITLE
Review unit tests

### ISSUE THREAD

**Issue by Dalstroem** [Dalstroem/FusionMVVM#24]
Unit test names should be consistent and easily understood. Write better tests.

**TODO:**
1. Choose a naming standard and stick to it.
2. Try AutoFixture.

**Comment by Ciesix** [comment]
Related to 1844e58d85fc71a5417d5cfbde15afdb4b5ed7a7.

**Comment by Ciesix** [comment]
Related to 5c884a1712fd4734559e0ef8dfbe612269494ecd, 890974ced400c2b9efe2fd6c1abb836233f806f9 and 17c37ef42bb92b608fae8cbb79739edf2c5e9068.
